services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t hlriffel/docker-react .

script:
  - docker run -e CI=true hlriffel/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: sa-east-1
#   app: docker-react
#   env: docker-react-env
#   bucket_name: A_BUCKET_NAME
#   bucket_path: A_BUCKET_PATH
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
